version: 2
jobs:
  build:
    docker:
      - image: bpicode/docker_golang
    working_directory: /root/go/src/github.com/bpicode/depbot
    steps:
      - checkout
      - run: go build
      - run: go test ./...

  upgrade_fritzctl_deps:
    docker:
      - image: bpicode/docker_golang
    working_directory: /root/go/src/github.com/bpicode/depbot
    steps:
      - checkout
      - run: go run main.go update --project=github.com/bpicode/fritzctl --token=$GITHUB_API_TOKEN

workflows:
  version: 2
  on_commit:
    jobs:
      - build:
          filters:
           branches:
              only:
                - master

  scheduled_upgrade_fritzctl_deps:
    triggers:
      - schedule:
          cron: "0 0 8 * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - upgrade_fritzctl_deps
